export enum Subjects {
    ORGANIZATION_CREATED = "organization:created",
    ORGANIZATION_UPDATED = "organization:updated",
    ORGANIZATION_DELETED = "organization:deleted",
    ORGANIZATION_VERIFIED = "organization:verified",
    ORGANIZATION_FORGET_PASSWORD = "organization:forgot-passord", 
    USER_CREATED = "user:created",
    USER_UPDATED = "user:updated",
    USER_DELETED = "user:deleted",
    USER_VERIFIED = "user:verified",
    USER_FORGOT_PASSWORD = "user:forgot-passord",
    ADMIN_CREATED = "admin:created",
    ADMIN_UPDATED = "admin:updated",
    ADMIN_DELETED = "admin:deleted",
    ADMIN_VERIFIED = "admin:verified",
    ADMIN_FORGOT_PASSWORD = "admin:forgot-passord",
    SURVEY_SCHEMA_CREATED = "survey_schema:created",
    SURVEY_SCHEMA_UPDATED = "survey_schema:updated",
    SURVEY_SCHEMA_DELETED = "survey_schema:deleted",
    SURVEY_DATA_CREATED = "survey_data:created"
}