export enum QuestionTypesEnum {
    SINGLE_SELECTION = "SINGLE_SELECTION",
    MULTIPLE_SELECTION = "MULTIPLE_SELECTION",
    RATING_STARS = "RATING_STARS",
    NET_PROMOTER_SCORE = "NET_PROMOTER_SCORE",
    OPEN_ENDED = "OPEN_ENDED" 
}