apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: survey.dev
      http:
        paths:
          - path: /api/organizations/?(.*)
            pathType: Prefix
            backend:
              service:
                name: organizations-srv
                port:
                  number: 3000