apiVersion: apps/v1
kind: Deployment
metadata:
  name: organizations-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organizations
  template:
    metadata:
      labels:
        app: organizations
    spec:
      containers:
      - name: organizations
        image: organizations
        imagePullPolicy: Never
        env:
          - name: MONGO_URI
            value: http://organizations-mongo-srv
          - name: JWT_SECRET
            valueFrom:
                secretKeyRef:
                  name: jsonwebtoken-secret
                  key: JWT_SECRET
          - name: COOKIE_SECRET
            valueFrom:
                secretKeyRef:
                  name: cookie-secret
                  key: COOKIE_SECRET
          
---

apiVersion: v1
kind: Service
metadata:
  name: organizations-srv
spec:
  selector:
    app: organizations
  ports:
  - port: 80
    targetPort: 3000

