apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: survey
  template:
    metadata:
      labels:
        app: survey
    spec:
      containers:
      - name: survey
        image: survey
        imagePullPolicy: Never
        env:
          - name: MONGO_URI
            value: mongodb://survey-mongo-srv:27017
          - name: JWT_SECRET
            valueFrom:
                secretKeyRef:
                  name: jsonwebtoken-secret
                  key: JWT_SECRET
          - name: COOKIE_SECRET
            valueFrom:
                secretKeyRef:
                  name: cookie-secret
                  key: COOKIE_SECRET
          
---

apiVersion: v1
kind: Service
metadata:
  name: survey-srv
spec:
  selector:
    app: survey
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000

