apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: surveyappacr.azurecr.io/users #change 'surveyappacr' with your <AZURE_CONTAINER_REGISTERY_SERVER>
        imagePullPolicy: Always
        env:
          - name: MONGO_URI
            value: mongodb://users-mongo-0.users-mongo-svc,users-mongo-1.users-mongo-svc:27017
          - name: JWT_SECRET
            valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
          - name: COOKIE_SECRET
            valueFrom:
                secretKeyRef:
                  name: cookie-secret
                  key: COOKIE_SECRET